version: '3'
services:
  postgres:
    image: 'postgres'
    container_name: 'postgres-maxxidata'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - ~/postgres-volume:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres-volume:
